### ISSUE TITLE
documentation is not 100% clear

### ISSUE THREAD

**Issue by kordan** [e-abc/notificationeabc#1]
Thanks for this plugin.
I find it is very useful.

I just meet it and I wonder what does it do in detail because the readme.md is does not go too much in detail.
I add here some questions I was facing during the plugin setup:
- "Active enrol alert"; Which alert? Were not we dealing about email? Why do I need to activate the alert? Wasn't I activating it enabling this plugin?
- "Active global" Active enrol notification for all site.; Why? Can I set this plugin for a subset of courses? How?
Please, provide a more detailed readme and, maybe, bound an help button to mform elements of enrol/notificationeabc/edit_form.php

Thanks again for your work!
Kordan

**Comment by e-abc** [comment]
Hi Kordan, Thanks for your feedback, we will take them into account.
Let me explain your doubts

- This plugin captures three types of events. "Enrol", "unenrol" and "update enrol". You can activate any of them, or none. Yes, we dealing about email, maybe we should change the option name.

- Yes, this plugin can be activated for any course. You just have to add it as a enrol method and configure the options.

We going to update de plugin soon and we will complete this documentation as well

Thanks
